version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tcc-api"
s3_bucket = "[bucket-name]"
s3_prefix = "tcc-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
